---
- name: Load apt key for docker engine
  apt_key: keyserver=hkp://p80.pool.sks-keyservers.net:80 id=58118E89F3A912897C070ADBF76221572C52609D
  become: yes

- name: Add docker repository
  apt_repository: repo='deb https://apt.dockerproject.org/repo ubuntu-xenial main' state=present filename='docker'
  become: yes

- name: Update apt cache
  apt: update_cache=yes cache_valid_time=86400
  become: yes

- name: Install docker-engine package
  apt: name=docker-engine
  register: aptinstall
  become: yes

- name: Install python-pip package
  apt: name=python-pip
  become: yes

- name: Install docker-py module
  pip: name=docker-py
  become: yes
  
- name: Create docker group
  group: name=docker state=present
  become: yes

- name: Add docker group to ansible
  user: name={{ ansible_user }} group=docker
  become: yes

#- name: Copy docker logging config
#  template:
#    src: templates/daemon.mapper.j2
#    dest: /etc/docker/daemon.mapper
#  become: yes

- name: Start docker engine
  service: name=docker state=started
  become: yes
  
- name: Restart machine
  shell: sleep 2 && shutdown -r now
  async: 1
  poll: 0
  become: true
  ignore_errors: true
  when: aptinstall.changed

- name: Waiting(60 sec) for server to come back
  local_action: wait_for host={{ inventory_hostname }} state=started delay=40 timeout=20
  become: false
  when: aptinstall.changed