---
kafka_user: kafka
kafka_group: kafka
kafka_conf_dir: /etc/kafka/config
kafka_log_dir: /var/log/kafka
kafka_version: 0.10.2.1
apache_mirror: apache.mirror.anlx.net
kafka_port: 9092
zookeeper_client_port: 2181