galaxy_info:
  author: Alexey Doroganov
  description: Install Docker
  company: Luxoft
  license: Apache
  min_ansible_version: 2.1
  platforms:
    - name: Ubuntu
      versions:
        - all
  galaxy_tags: []
dependencies: []