galaxy_info:
  author: Alexey Doroganov
  description: Install Luxoft CA certificates
  company: Luxoft
  license: Apache
  min_ansible_version: 1.2
  platforms:
    - name: Ubuntu
      versions:
        - all
  galaxy_tags: []
dependencies: []