---
- name: Reload systemd
  command: systemctl daemon-reload
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "7"

- name: Restart zookeeper
  service: name=zookeeper-server enabled=yes state=restarted
