// Code generated by protoc-gen-go.
// source: TestChaincode.proto
// DO NOT EDIT!

/*
Package main is a generated protocol buffer package.

It is generated from these files:
	TestChaincode.proto

It has these top-level messages:
	Entity
	GetEntity
	HistoryItem
	History
*/
package main

import "github.com/golang/protobuf/proto"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal

type Type int32

const (
	Type_DEFAULT = 0
	Type_COMPANY = 1
	Type_USER    = 2
)

var Type_name = map[int32]string{
	0: "DEFAULT",
	1: "COMPANY",
	2: "USER",
}
var Type_value = map[string]int32{
	"DEFAULT": 0,
	"COMPANY": 1,
	"USER":    2,
}

func (x Type) String() string {
	return proto.EnumName(Type_name, int32(x))
}

type Entity struct {
	Name        string `protobuf:"bytes,1,opt" json:"Name,omitempty"`
	Description string `protobuf:"bytes,2,opt" json:"Description,omitempty"`
	Type        Type   `protobuf:"varint,3,opt,name=type,enum=main.Type" json:"type,omitempty"`
}

func (m *Entity) Reset()         { *m = Entity{} }
func (m *Entity) String() string { return proto.CompactTextString(m) }
func (*Entity) ProtoMessage()    {}

type GetEntity struct {
	Name string `protobuf:"bytes,1,opt" json:"Name,omitempty"`
}

func (m *GetEntity) Reset()         { *m = GetEntity{} }
func (m *GetEntity) String() string { return proto.CompactTextString(m) }
func (*GetEntity) ProtoMessage()    {}

type HistoryItem struct {
	TxId      string  `protobuf:"bytes,1,opt" json:"TxId,omitempty"`
	Value     *Entity `protobuf:"bytes,2,opt,name=value" json:"value,omitempty"`
	Timestamp int64   `protobuf:"varint,3,opt,name=timestamp" json:"timestamp,omitempty"`
	IsDelete  bool    `protobuf:"varint,4,opt,name=isDelete" json:"isDelete,omitempty"`
}

func (m *HistoryItem) Reset()         { *m = HistoryItem{} }
func (m *HistoryItem) String() string { return proto.CompactTextString(m) }
func (*HistoryItem) ProtoMessage()    {}

func (m *HistoryItem) GetValue() *Entity {
	if m != nil {
		return m.Value
	}
	return nil
}

type History struct {
	History []*HistoryItem `protobuf:"bytes,1,rep,name=history" json:"history,omitempty"`
	Key     string         `protobuf:"bytes,2,opt,name=key" json:"key,omitempty"`
}

func (m *History) Reset()         { *m = History{} }
func (m *History) String() string { return proto.CompactTextString(m) }
func (*History) ProtoMessage()    {}

func (m *History) GetHistory() []*HistoryItem {
	if m != nil {
		return m.History
	}
	return nil
}

func init() {
	proto.RegisterEnum("main.Type", Type_name, Type_value)
}
