// Code generated by protoc-gen-go. DO NOT EDIT.
// source: TestChaincode.proto

/*
Package main is a generated protocol buffer package.

It is generated from these files:
	TestChaincode.proto

It has these top-level messages:
	Entity
	GetEntity
	HistoryItem
	History
*/
package main

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Type int32

const (
	Type_DEFAULT Type = 0
	Type_COMPANY Type = 1
	Type_USER    Type = 2
)

var Type_name = map[int32]string{
	0: "DEFAULT",
	1: "COMPANY",
	2: "USER",
}
var Type_value = map[string]int32{
	"DEFAULT": 0,
	"COMPANY": 1,
	"USER":    2,
}

func (x Type) String() string {
	return proto.EnumName(Type_name, int32(x))
}
func (Type) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type Entity struct {
	Name        string `protobuf:"bytes,1,opt,name=Name,json=name" json:"Name,omitempty"`
	Description string `protobuf:"bytes,2,opt,name=Description,json=description" json:"Description,omitempty"`
	Type        Type   `protobuf:"varint,3,opt,name=type,enum=main.Type" json:"type,omitempty"`
}

func (m *Entity) Reset()                    { *m = Entity{} }
func (m *Entity) String() string            { return proto.CompactTextString(m) }
func (*Entity) ProtoMessage()               {}
func (*Entity) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Entity) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Entity) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Entity) GetType() Type {
	if m != nil {
		return m.Type
	}
	return Type_DEFAULT
}

type GetEntity struct {
	Name string `protobuf:"bytes,1,opt,name=Name,json=name" json:"Name,omitempty"`
}

func (m *GetEntity) Reset()                    { *m = GetEntity{} }
func (m *GetEntity) String() string            { return proto.CompactTextString(m) }
func (*GetEntity) ProtoMessage()               {}
func (*GetEntity) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *GetEntity) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type HistoryItem struct {
	TxId      string  `protobuf:"bytes,1,opt,name=TxId,json=txId" json:"TxId,omitempty"`
	Value     *Entity `protobuf:"bytes,2,opt,name=value" json:"value,omitempty"`
	Timestamp int64   `protobuf:"varint,3,opt,name=timestamp" json:"timestamp,omitempty"`
	IsDelete  bool    `protobuf:"varint,4,opt,name=isDelete" json:"isDelete,omitempty"`
}

func (m *HistoryItem) Reset()                    { *m = HistoryItem{} }
func (m *HistoryItem) String() string            { return proto.CompactTextString(m) }
func (*HistoryItem) ProtoMessage()               {}
func (*HistoryItem) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *HistoryItem) GetTxId() string {
	if m != nil {
		return m.TxId
	}
	return ""
}

func (m *HistoryItem) GetValue() *Entity {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *HistoryItem) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *HistoryItem) GetIsDelete() bool {
	if m != nil {
		return m.IsDelete
	}
	return false
}

type History struct {
	History []*HistoryItem `protobuf:"bytes,1,rep,name=history" json:"history,omitempty"`
	Key     string         `protobuf:"bytes,2,opt,name=key" json:"key,omitempty"`
}

func (m *History) Reset()                    { *m = History{} }
func (m *History) String() string            { return proto.CompactTextString(m) }
func (*History) ProtoMessage()               {}
func (*History) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *History) GetHistory() []*HistoryItem {
	if m != nil {
		return m.History
	}
	return nil
}

func (m *History) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func init() {
	proto.RegisterType((*Entity)(nil), "main.Entity")
	proto.RegisterType((*GetEntity)(nil), "main.GetEntity")
	proto.RegisterType((*HistoryItem)(nil), "main.HistoryItem")
	proto.RegisterType((*History)(nil), "main.History")
	proto.RegisterEnum("main.Type", Type_name, Type_value)
}

func init() { proto.RegisterFile("TestChaincode.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 334 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x51, 0x4d, 0x4f, 0xab, 0x40,
	0x14, 0x7d, 0x14, 0x5e, 0x3f, 0x2e, 0xef, 0xbd, 0xf0, 0xc6, 0x0d, 0x31, 0x46, 0x09, 0x2b, 0x52,
	0x13, 0x16, 0x75, 0xe1, 0xba, 0x5f, 0xda, 0x26, 0x5a, 0x0d, 0xd2, 0x85, 0x2e, 0x4c, 0xa6, 0x70,
	0x9b, 0x4e, 0xda, 0x61, 0x08, 0xdc, 0x9a, 0xb2, 0xf2, 0xaf, 0x1b, 0xa0, 0xb5, 0xba, 0x70, 0x77,
	0xef, 0x39, 0x27, 0xf7, 0x9c, 0x99, 0x03, 0x27, 0x21, 0xe6, 0x34, 0x5c, 0x71, 0x91, 0x44, 0x2a,
	0x46, 0x3f, 0xcd, 0x14, 0x29, 0x66, 0x48, 0x2e, 0x12, 0xf7, 0x15, 0x9a, 0xe3, 0x84, 0x04, 0x15,
	0x8c, 0x81, 0x31, 0xe3, 0x12, 0x6d, 0xcd, 0xd1, 0xbc, 0x4e, 0x60, 0x24, 0x5c, 0x22, 0x73, 0xc0,
	0x1c, 0x61, 0x1e, 0x65, 0x22, 0x25, 0xa1, 0x12, 0xbb, 0x51, 0x51, 0x66, 0x7c, 0x84, 0xd8, 0x39,
	0x18, 0x54, 0xa4, 0x68, 0xeb, 0x8e, 0xe6, 0xfd, 0xeb, 0x81, 0x5f, 0x1e, 0xf5, 0xc3, 0x22, 0xc5,
	0xa0, 0xc2, 0xdd, 0x0b, 0xe8, 0xdc, 0x22, 0xfd, 0x6c, 0xe1, 0xbe, 0x83, 0x39, 0x11, 0x39, 0xa9,
	0xac, 0x98, 0x12, 0xca, 0x52, 0x12, 0xee, 0xa6, 0xf1, 0x41, 0x42, 0xbb, 0x69, 0xcc, 0x5c, 0xf8,
	0xfd, 0xc6, 0x37, 0x5b, 0xac, 0xfc, 0xcd, 0xde, 0x9f, 0xda, 0xa4, 0xbe, 0x19, 0xd4, 0x14, 0x3b,
	0x83, 0x0e, 0x09, 0x89, 0x39, 0x71, 0x99, 0x56, 0x61, 0xf4, 0xe0, 0x08, 0xb0, 0x53, 0x68, 0x8b,
	0x7c, 0x84, 0x1b, 0x24, 0xb4, 0x0d, 0x47, 0xf3, 0xda, 0xc1, 0xe7, 0xee, 0x4e, 0xa0, 0xb5, 0x0f,
	0xc0, 0x2e, 0xa1, 0xb5, 0xaa, 0x47, 0x5b, 0x73, 0x74, 0xcf, 0xec, 0xfd, 0xaf, 0xad, 0xbe, 0x04,
	0x0c, 0x0e, 0x0a, 0x66, 0x81, 0xbe, 0xc6, 0x62, 0xff, 0x27, 0xe5, 0xd8, 0xed, 0x82, 0x51, 0xbe,
	0x9c, 0x99, 0xd0, 0x1a, 0x8d, 0x6f, 0xfa, 0xf3, 0xbb, 0xd0, 0xfa, 0x55, 0x2e, 0xc3, 0x87, 0xfb,
	0xc7, 0xfe, 0xec, 0xd9, 0xd2, 0x58, 0x1b, 0x8c, 0xf9, 0xd3, 0x38, 0xb0, 0x1a, 0x83, 0x6b, 0x70,
	0x22, 0x25, 0xfd, 0xcd, 0x76, 0xa7, 0x96, 0xe4, 0xe7, 0xeb, 0x32, 0x8b, 0x4a, 0xfc, 0x25, 0x5f,
	0x64, 0x22, 0xaa, 0x1b, 0x1a, 0xfc, 0xfd, 0x56, 0xdb, 0x4b, 0x55, 0xd8, 0xa2, 0x59, 0x71, 0x57,
	0x1f, 0x01, 0x00, 0x00, 0xff, 0xff, 0xa3, 0xdf, 0x92, 0x4a, 0xd4, 0x01, 0x00, 0x00,
}
