---
- name: Restart iptables
  service: name=iptables state=restarted enabled=yes

- name: Reload firewalld
  command: firewall-cmd --reload

- name: Run update-grub
  shell: "{{ update_grub }}"
  when: ansible_distribution_major_version|int > 6
