{
 "title": "Quick Summary",
 "time": { "from": "now/d", "to": "now" },
 "panels": [
  {
   "title": "Transactions per second",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(rate(ledger_transaction_count[1m]))"
    }
   ]
  },
  {
   "title": "Failures per second during  last minute",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 0 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "expr": "sum(rate(chaincode_execute_timeouts[1m]))"
    },
    {
     "expr": "sum(rate(chaincode_launch_failures[1h]))"
    },
    {
     "expr": "sum(rate(chaincode_launch_timeouts[1h]))"
    },
    {
     "expr": "sum(rate(endorser_chaincode_instantiation_failures[1h]))"
    },
    {
     "expr": "sum(rate(endorser_duplicate_transaction_failures[1h]))"
    },
    {
     "expr": "sum(rate(endorser_endorsement_failures[1h]))"
    },
    {
     "expr": "sum(rate(endorser_proposal_acl_failures[1h]))"
    },
    {
     "expr": "sum(rate(endorser_proposal_validation_failures[1h]))"
    }
   ]
  },
  {
   "title": "Ledger Height Per Channel",
   "type": "table",
   "gridPos": { "h": 4, "w": 8, "x": 6, "y": 0 },
   "targets": [
    { "expr": "ledger_blockchain_height" }
   ]
  },
  {
   "title": "Live Monitored Nodes",
   "type": "table",
   "gridPos": { "h": 4, "w": 8, "x": 14, "y": 0 },
   "targets": [
    { "expr": "fabric_version" }
   ]
  },
  {
   "title": "Block procesing time",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "ledger_block_processing_time_bucket\n",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Amount of business transactions per channel",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(ledger_transaction_count{transaction_type=\"ENDORSER_TRANSACTION\"}) by (channel)"
    }
   ]
  }
 ]
}