---
- name: purge kafka
  ignore_errors: yes
  become: yes
  raw: "for var in $(/opt/kafka/bin/kafka-topics.sh --zookeeper {{hostvars[groups['zookeeper'][0]]['ansible_host']}}:2181 --list); do /opt/kafka/bin/kafka-topics.sh --zookeeper {{hostvars[groups['zookeeper'][0]]['ansible_host']}}:2181 --delete --topic $var; done"

- name: Waiting 60 sec for complete cleanup
  pause:
    minutes: 1