packages:
  - java-1.8.0-openjdk-devel
  - python-simplejson
  - python-httplib2
  - man
  - man-pages
  - vim-enhanced
  - sysstat
  - lsof
  - jwhois
  - nc
  - libselinux-python
  - ntp
  - parted
  - openssh-clients
  - iotop
  - unzip
  - curl
  - wget
  - xfsprogs

ntp_service: ntpd
ntp_sync: "/usr/sbin/ntpd -gq"

epel_rpm_url: "http://dl.fedoraproject.org/pub/epel/epel-release-latest-6.noarch.rpm"
epel_yum: "epel-release"

datastax_repo: "redhat-datastax_repo.j2"
datastax_repo_file: "/etc/yum.repos.d/datastax.repo"
datastax_repo_key: "http://rpm.datastax.com/rpm/repo_key"
