#
# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#
version: '2'

services:

  ca.luxoft.com:
    container_name: ca.luxoft.com
    image: hyperledger/fabric-ca:1.4.0
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.luxoft.com-cert.pem
      - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server-config/2ed7d348a31c39506ccfcdc0f124f6803ce5b9f56ec8181f9ba285edc9fbd47f_sk
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.luxoft.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/2ed7d348a31c39506ccfcdc0f124f6803ce5b9f56ec8181f9ba285edc9fbd47f_sk
    ports:
      - "7054:7054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - ../crypto-config/peerOrganizations/luxoft.com/ca/:/etc/hyperledger/fabric-ca-server-config

  orderer.luxoft.com:
    container_name: orderer.luxoft.com
    image: hyperledger/fabric-orderer:1.4.0
    environment:
      - FABRIC_LOGGING_SPEC=debug
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/etc/hyperledger/configtx/genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/etc/hyperledger/crypto/orderer/msp
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/etc/hyperledger/crypto/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/etc/hyperledger/crypto/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/etc/hyperledger/crypto/orderer/tls/ca.crt, /etc/hyperledger/crypto/peerOrg1/tls/ca.crt]
      - ORDERER_OPERATIONS_LISTENADDRESS=0.0.0.0:9444
      - ORDERER_METRICS_PROVIDER=prometheus
      - ORDERER_OPERATIONS_TLS_ENABLED=true
      - ORDERER_OPERATIONS_TLS_PRIVATEKEY=/etc/hyperledger/crypto/orderer/tls/server.key
      - ORDERER_OPERATIONS_TLS_CERTIFICATE=/etc/hyperledger/crypto/orderer/tls/server.crt
      - ORDERER_OPERATIONS_TLS_CLIENTROOTCAS=[/etc/hyperledger/crypto/orderer/tls/ca.crt]
      - ORDERER_OPERATIONS_TLS_CLIENTAUTHREQUIRED=true
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/orderers
    command: orderer
    ports:
      - 7050:7050
      - 9444:9444
    volumes:
        - ../channel-artifacts:/etc/hyperledger/configtx
        - ../crypto-config/ordererOrganizations/luxoft.com/orderers/orderer.luxoft.com/:/etc/hyperledger/crypto/orderer
        - ../crypto-config/peerOrganizations/luxoft.com/peers/peer0.luxoft.com/:/etc/hyperledger/crypto/peerOrg1
        # Having orderer.yaml here is workaround for bug in this file in fabric 1.4. It lacks ClientRootCAs variable
        - ./orderer.yaml:/etc/hyperledger/fabric/orderer.yaml

  peer0.luxoft.com:
    container_name: peer0.luxoft.com
    extends:
      file:   base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.luxoft.com
      - CORE_PEER_LOCALMSPID=Org1MSP
      - CORE_PEER_ADDRESS=peer0.luxoft.com:7051
      - CORE_OPERATIONS_LISTENADDRESS=0.0.0.0:9443
      - CORE_METRICS_PROVIDER=prometheus
      - CORE_OPERATIONS_TLS_ENABLED=true
      - CORE_OPERATIONS_TLS_KEY_FILE=/etc/hyperledger/crypto/peer/tls/server.key
      - CORE_OPERATIONS_TLS_CERT_FILE=/etc/hyperledger/crypto/peer/tls/server.crt
      - CORE_OPERATIONS_TLS_CLIENTAUTHREQUIRED=true
      - CORE_OPERATIONS_TLS_CLIENTROOTCAS_FILES=/etc/hyperledger/crypto/peer/tls/ca.crt
    ports:
      - 7051:7051
      - 7053:7053
      - 9443:9443
    volumes:
        - ../crypto-config/peerOrganizations/luxoft.com/peers/peer0.luxoft.com/:/etc/hyperledger/crypto/peer
    depends_on:
      - orderer.luxoft.com

  peer1.luxoft.com:
    container_name: peer1.luxoft.com
    extends:
      file:   base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.luxoft.com
      - CORE_PEER_LOCALMSPID=Org1MSP
      - CORE_PEER_ADDRESS=peer1.luxoft.com:7051
    ports:
      - 7061:7051
      - 7063:7053
    volumes:
        - ../crypto-config/peerOrganizations/luxoft.com/peers/peer1.luxoft.com/:/etc/hyperledger/crypto/peer
    depends_on:
      - orderer.luxoft.com

  ccenv:
    image: hyperledger/fabric-ccenv:1.4.0

  prometheus.luxoft.com:
    container_name: prometheus.luxoft.com
    image: prom/prometheus:v2.7.1
    ports:
      - 9090:9090/tcp
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ../crypto-config/prometheusOrganizations/luxoft.com/tls:/etc/prometheus/tls
    depends_on:
      - peer0.luxoft.com

  grafana.luxoft.com:
    container_name: grafana.luxoft.com
    image: grafana/grafana:5.4.3
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=secret
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning/
    ports:
      - 3000:3000/tcp
    volumes:
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    depends_on:
      - prometheus.luxoft.com