galaxy_info:
  author: Nikita Volkov
  description: Fabric 1.0.0 orderer
  company: Luxoft
  license: Apache
  min_ansible_version: 2.1
  platforms:
    - name: Ubuntu
      versions:
        - all
  galaxy_tags: []

dependencies: