---
# defaults file for prometheus-server-docker
scrape_configs_peers: "{{ [ { 'name':'fabric peers', 'targets':groups['tag_project_group_peers']|default([])|map('regex_replace','^(.*)$','\\1:9443') |list} ] }} "
scrape_configs_orderers: "{{ [ { 'name':'fabric orderers', 'targets':groups['tag_project_group_orderers']|default([])|map('regex_replace','^(.*)$','\\1:9443') |list} ] }}"
node_name: "prometheus.organisation{{organisation_index}}"
domain: luxoft.com
crypto_config_path: ../../../../network/crypto-config
organisation_index: "0"